# Generated by Django 3.0.8 on 2020-09-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200921_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
